### ISSUE TITLE
New install, no high and low values reported

### ISSUE THREAD

**Issue by summitbri** [briis/hass-weatherflow2mqtt#103]
I've only been running this for about 4 days via the HA add-on v 2.2.4.  Awesome integration!  

One issue I've discovered is that there are no daily min/max values calculated.  Here's an example of the state attributes for wf_temperature:

state_class: measurement
attribution: Powered by WeatherFlow2MQTT
brand: WeatherFlow
max_day: None
max_day_time: '2021-11-26T23:21:33+00:00'
max_month: None
max_month_time: '2021-11-26T23:21:33+00:00'
max_all: '-9999.0'
max_all_time: None
min_day: None
min_day_time: '2021-11-26T23:21:33+00:00'
min_month: None
min_month_time: '2021-11-26T23:21:33+00:00'
min_all: None
min_all_time: '2021-11-26T23:21:33+00:00'
unit_of_measurement: °F
friendly_name: WF Temperature
device_class: temperature

**Comment by briis** [comment]
Glad it is useful. It is hard to say from the above what is wrong as there are no errors. Maybe turn on debug in the Add-On and see if something shows up there.

But anyway, all these sensors are marked as `state_class: measurement`, which means that they are collecting data for long term statistics, and you can use them in HA like [described here](https://www.home-assistant.io/blog/2021/09/01/release-20219/#long-term-statistics-unlocked-for-all-sensors)

The above basically makes the calculated values you see as attributes redundant, and they will be deprecated soon.

**Comment by summitbri** [comment]
Hi and thanks for the quick response.

I got this error in the debug:
ERROR:weatherflow2mqtt.sqlite:Could write to High and Low Table. Error message: '>' not supported between instances of 'float' and 'NoneType'

I'll take another look at the sensors' state_class, I may have overlooked that approach.  Thx!

**Comment by briis** [comment]
For some reason no data is either in the current Database or no data is send to the update function. Are you seeing values in the rain_today, rain_yesterday or lightning fields?

**Comment by summitbri** [comment]
Yup, I see values in all three of those...

**Comment by briis** [comment]
OK, so the database is present and working. Let me see if I can make an update that collects better data on what exactly goes wrong.

**Comment by briis** [comment]
Should be fixed in the latest 3.0.3 release. Could you test, and report back?

**Comment by summitbri** [comment]
Hi there, thanks for the work but not yet resolved.  Here is the error I see in the log:

ERROR:weatherflow2mqtt.sqlite:Could not write to High and Low Table. Error message: '>' not supported between instances of 'float' and 'NoneType'

**Comment by briis** [comment]
Could you find the SQLite database and attach it here (Just Zip it in a file). It seems that it is not correctly created, and missing some fields.

Alternativ, if you understand SQL commands, list the table `high_low` which is the table we are trying to write to.

**Comment by summitbri** [comment]
Hi, sorry for slow reply.  I am running this as an HA add on, so not sure how to extract the database from the container.  Might be beyond my skill level!

**Comment by natekspencer** [comment]
> Hi, sorry for slow reply. I am running this as an HA add on, so not sure how to extract the database from the container. Might be beyond my skill level!

The easiest way to do this with the add-on is to do a partial backup of from supervisor, select "WeatherFlow to MQTT" and then download the backup.

**Comment by summitbri** [comment]
Easy, @briis I just sent you an email with the link.

**Comment by briis** [comment]
Got it. Will look if there is anything wrong with that. Normally best way to resolve these issue, if you don't have too much data, is to stop the Add-On/Container and then delete the database. It should then be recreated and hopefully start working.

But I will look in to the data you send first.

**Comment by summitbri** [comment]
Ok let me know.  I pipe the data from HA to influxdb so it would be fine to delete the database if needed.

**Comment by briis** [comment]
Checked through the database, and it is missing initial  values in most of the max and min day fields, and when they are NULL then a lot of the comparison we do during updates will not work and nothing will be written.

If you don't mind losing the data data, I suggest to try and delete the database file and let it be initialized again. Remember to Stop the Container before you delete `weatherflow2mqtt.db`, as the creation of the empty database only occurs upon startup.

Let us know how this goes.

**Comment by summitbri** [comment]
Deleting the database file seemed to fix it, at least the daily.  I'm assuming the other intervals will work as well.  Thanks!

**Comment by briis** [comment]
Good to hear. I will close this issue now.
